
package de.webpdf.sample.stubs.barcode;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BarcodeService", targetNamespace = "http://schema.webpdf.de/1.0/soap/barcode", wsdlLocation = "http://localhost:8080/webPDF/soap/barcode?wsdl")
public class BarcodeService
    extends Service
{

    private final static URL BARCODESERVICE_WSDL_LOCATION;
    private final static WebServiceException BARCODESERVICE_EXCEPTION;
    private final static QName BARCODESERVICE_QNAME = new QName("http://schema.webpdf.de/1.0/soap/barcode", "BarcodeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webPDF/soap/barcode?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BARCODESERVICE_WSDL_LOCATION = url;
        BARCODESERVICE_EXCEPTION = e;
    }

    public BarcodeService() {
        super(__getWsdlLocation(), BARCODESERVICE_QNAME);
    }

    public BarcodeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BARCODESERVICE_QNAME, features);
    }

    public BarcodeService(URL wsdlLocation) {
        super(wsdlLocation, BARCODESERVICE_QNAME);
    }

    public BarcodeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BARCODESERVICE_QNAME, features);
    }

    public BarcodeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BarcodeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Barcode
     */
    @WebEndpoint(name = "BarcodePort")
    public Barcode getBarcodePort() {
        return super.getPort(new QName("http://schema.webpdf.de/1.0/soap/barcode", "BarcodePort"), Barcode.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Barcode
     */
    @WebEndpoint(name = "BarcodePort")
    public Barcode getBarcodePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schema.webpdf.de/1.0/soap/barcode", "BarcodePort"), Barcode.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BARCODESERVICE_EXCEPTION!= null) {
            throw BARCODESERVICE_EXCEPTION;
        }
        return BARCODESERVICE_WSDL_LOCATION;
    }

}
