//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webPDFWebServiceTest.BarcodeService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/soap/barcode")]
    public partial class FaultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class BarcodeSelectionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RectangleType scanAreaField;
        
        private string pagesField;
        
        private int resolutionField;
        
        private bool resolutionFieldSpecified;
        
        private bool pureBarcodeField;
        
        private bool pureBarcodeFieldSpecified;
        
        private bool gs1Field;
        
        private bool gs1FieldSpecified;
        
        private bool tryHarderField;
        
        private bool tryHarderFieldSpecified;
        
        private string allowedLengthsField;
        
        private bool barcode39CheckDigitField;
        
        private bool barcode39CheckDigitFieldSpecified;
        
        private bool codabarStartEndDigitsField;
        
        private bool codabarStartEndDigitsFieldSpecified;
        
        private string upcEanExtensionsField;
        
        private string charsetField;
        
        private string formatsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RectangleType scanArea {
            get {
                return this.scanAreaField;
            }
            set {
                this.scanAreaField = value;
                this.RaisePropertyChanged("scanArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
                this.RaisePropertyChanged("pages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int resolution {
            get {
                return this.resolutionField;
            }
            set {
                this.resolutionField = value;
                this.RaisePropertyChanged("resolution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resolutionSpecified {
            get {
                return this.resolutionFieldSpecified;
            }
            set {
                this.resolutionFieldSpecified = value;
                this.RaisePropertyChanged("resolutionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool pureBarcode {
            get {
                return this.pureBarcodeField;
            }
            set {
                this.pureBarcodeField = value;
                this.RaisePropertyChanged("pureBarcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pureBarcodeSpecified {
            get {
                return this.pureBarcodeFieldSpecified;
            }
            set {
                this.pureBarcodeFieldSpecified = value;
                this.RaisePropertyChanged("pureBarcodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool gs1 {
            get {
                return this.gs1Field;
            }
            set {
                this.gs1Field = value;
                this.RaisePropertyChanged("gs1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gs1Specified {
            get {
                return this.gs1FieldSpecified;
            }
            set {
                this.gs1FieldSpecified = value;
                this.RaisePropertyChanged("gs1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool tryHarder {
            get {
                return this.tryHarderField;
            }
            set {
                this.tryHarderField = value;
                this.RaisePropertyChanged("tryHarder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tryHarderSpecified {
            get {
                return this.tryHarderFieldSpecified;
            }
            set {
                this.tryHarderFieldSpecified = value;
                this.RaisePropertyChanged("tryHarderSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string allowedLengths {
            get {
                return this.allowedLengthsField;
            }
            set {
                this.allowedLengthsField = value;
                this.RaisePropertyChanged("allowedLengths");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool barcode39CheckDigit {
            get {
                return this.barcode39CheckDigitField;
            }
            set {
                this.barcode39CheckDigitField = value;
                this.RaisePropertyChanged("barcode39CheckDigit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool barcode39CheckDigitSpecified {
            get {
                return this.barcode39CheckDigitFieldSpecified;
            }
            set {
                this.barcode39CheckDigitFieldSpecified = value;
                this.RaisePropertyChanged("barcode39CheckDigitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool codabarStartEndDigits {
            get {
                return this.codabarStartEndDigitsField;
            }
            set {
                this.codabarStartEndDigitsField = value;
                this.RaisePropertyChanged("codabarStartEndDigits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codabarStartEndDigitsSpecified {
            get {
                return this.codabarStartEndDigitsFieldSpecified;
            }
            set {
                this.codabarStartEndDigitsFieldSpecified = value;
                this.RaisePropertyChanged("codabarStartEndDigitsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string upcEanExtensions {
            get {
                return this.upcEanExtensionsField;
            }
            set {
                this.upcEanExtensionsField = value;
                this.RaisePropertyChanged("upcEanExtensions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string charset {
            get {
                return this.charsetField;
            }
            set {
                this.charsetField = value;
                this.RaisePropertyChanged("charset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string formats {
            get {
                return this.formatsField;
            }
            set {
                this.formatsField = value;
                this.RaisePropertyChanged("formats");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class RectangleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float widthField;
        
        private bool widthFieldSpecified;
        
        private float heightField;
        
        private bool heightFieldSpecified;
        
        private float xField;
        
        private bool xFieldSpecified;
        
        private float yField;
        
        private bool yFieldSpecified;
        
        private MetricsType metricsField;
        
        private bool metricsFieldSpecified;
        
        private CoordinatesType coordinatesField;
        
        private bool coordinatesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("heightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
                this.RaisePropertyChanged("xSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
                this.RaisePropertyChanged("ySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MetricsType metrics {
            get {
                return this.metricsField;
            }
            set {
                this.metricsField = value;
                this.RaisePropertyChanged("metrics");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metricsSpecified {
            get {
                return this.metricsFieldSpecified;
            }
            set {
                this.metricsFieldSpecified = value;
                this.RaisePropertyChanged("metricsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CoordinatesType coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
                this.RaisePropertyChanged("coordinates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coordinatesSpecified {
            get {
                return this.coordinatesFieldSpecified;
            }
            set {
                this.coordinatesFieldSpecified = value;
                this.RaisePropertyChanged("coordinatesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum MetricsType {
        
        /// <remarks/>
        px,
        
        /// <remarks/>
        mm,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum CoordinatesType {
        
        /// <remarks/>
        pdf,
        
        /// <remarks/>
        user,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpcaBarcodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItfBarcodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ean8BarcodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ean13BarcodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Code39BarcodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Code128BarcodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CodabarBarcodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataMatrixBarcodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pdf417BarcodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QrBarcodeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AztecBarcodeType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class BaseBarcodeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RectangleType positionField;
        
        private string charsetField;
        
        private string valueField;
        
        private int rotationField;
        
        private bool rotationFieldSpecified;
        
        private int marginField;
        
        private bool marginFieldSpecified;
        
        private string pagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RectangleType position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string charset {
            get {
                return this.charsetField;
            }
            set {
                this.charsetField = value;
                this.RaisePropertyChanged("charset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
                this.RaisePropertyChanged("rotation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rotationSpecified {
            get {
                return this.rotationFieldSpecified;
            }
            set {
                this.rotationFieldSpecified = value;
                this.RaisePropertyChanged("rotationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int margin {
            get {
                return this.marginField;
            }
            set {
                this.marginField = value;
                this.RaisePropertyChanged("margin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool marginSpecified {
            get {
                return this.marginFieldSpecified;
            }
            set {
                this.marginFieldSpecified = value;
                this.RaisePropertyChanged("marginSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
                this.RaisePropertyChanged("pages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class UpcaBarcodeType : BaseBarcodeType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class ItfBarcodeType : BaseBarcodeType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class Ean8BarcodeType : BaseBarcodeType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class Ean13BarcodeType : BaseBarcodeType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class Code39BarcodeType : BaseBarcodeType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class Code128BarcodeType : BaseBarcodeType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class CodabarBarcodeType : BaseBarcodeType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class DataMatrixBarcodeType : BaseBarcodeType {
        
        private int errorCorrectionField;
        
        private bool errorCorrectionFieldSpecified;
        
        private DataMatrixShapeType shapeField;
        
        private bool shapeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int errorCorrection {
            get {
                return this.errorCorrectionField;
            }
            set {
                this.errorCorrectionField = value;
                this.RaisePropertyChanged("errorCorrection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCorrectionSpecified {
            get {
                return this.errorCorrectionFieldSpecified;
            }
            set {
                this.errorCorrectionFieldSpecified = value;
                this.RaisePropertyChanged("errorCorrectionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataMatrixShapeType shape {
            get {
                return this.shapeField;
            }
            set {
                this.shapeField = value;
                this.RaisePropertyChanged("shape");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shapeSpecified {
            get {
                return this.shapeFieldSpecified;
            }
            set {
                this.shapeFieldSpecified = value;
                this.RaisePropertyChanged("shapeSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum DataMatrixShapeType {
        
        /// <remarks/>
        @default,
        
        /// <remarks/>
        rectangle,
        
        /// <remarks/>
        square,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class Pdf417BarcodeType : BaseBarcodeType {
        
        private int errorCorrectionField;
        
        private bool errorCorrectionFieldSpecified;
        
        private bool compactField;
        
        private bool compactFieldSpecified;
        
        private Pdf417CompactionModeType compactionModeField;
        
        private bool compactionModeFieldSpecified;
        
        private int dataCodewordsMinField;
        
        private bool dataCodewordsMinFieldSpecified;
        
        private int dataCodewordsMaxField;
        
        private bool dataCodewordsMaxFieldSpecified;
        
        private int symbolsPerCodewordMinField;
        
        private bool symbolsPerCodewordMinFieldSpecified;
        
        private int symbolsPerCodewordMaxField;
        
        private bool symbolsPerCodewordMaxFieldSpecified;
        
        private DataMatrixShapeType shapeField;
        
        private bool shapeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int errorCorrection {
            get {
                return this.errorCorrectionField;
            }
            set {
                this.errorCorrectionField = value;
                this.RaisePropertyChanged("errorCorrection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCorrectionSpecified {
            get {
                return this.errorCorrectionFieldSpecified;
            }
            set {
                this.errorCorrectionFieldSpecified = value;
                this.RaisePropertyChanged("errorCorrectionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool compact {
            get {
                return this.compactField;
            }
            set {
                this.compactField = value;
                this.RaisePropertyChanged("compact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compactSpecified {
            get {
                return this.compactFieldSpecified;
            }
            set {
                this.compactFieldSpecified = value;
                this.RaisePropertyChanged("compactSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Pdf417CompactionModeType compactionMode {
            get {
                return this.compactionModeField;
            }
            set {
                this.compactionModeField = value;
                this.RaisePropertyChanged("compactionMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compactionModeSpecified {
            get {
                return this.compactionModeFieldSpecified;
            }
            set {
                this.compactionModeFieldSpecified = value;
                this.RaisePropertyChanged("compactionModeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int dataCodewordsMin {
            get {
                return this.dataCodewordsMinField;
            }
            set {
                this.dataCodewordsMinField = value;
                this.RaisePropertyChanged("dataCodewordsMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataCodewordsMinSpecified {
            get {
                return this.dataCodewordsMinFieldSpecified;
            }
            set {
                this.dataCodewordsMinFieldSpecified = value;
                this.RaisePropertyChanged("dataCodewordsMinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int dataCodewordsMax {
            get {
                return this.dataCodewordsMaxField;
            }
            set {
                this.dataCodewordsMaxField = value;
                this.RaisePropertyChanged("dataCodewordsMax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataCodewordsMaxSpecified {
            get {
                return this.dataCodewordsMaxFieldSpecified;
            }
            set {
                this.dataCodewordsMaxFieldSpecified = value;
                this.RaisePropertyChanged("dataCodewordsMaxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int symbolsPerCodewordMin {
            get {
                return this.symbolsPerCodewordMinField;
            }
            set {
                this.symbolsPerCodewordMinField = value;
                this.RaisePropertyChanged("symbolsPerCodewordMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool symbolsPerCodewordMinSpecified {
            get {
                return this.symbolsPerCodewordMinFieldSpecified;
            }
            set {
                this.symbolsPerCodewordMinFieldSpecified = value;
                this.RaisePropertyChanged("symbolsPerCodewordMinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int symbolsPerCodewordMax {
            get {
                return this.symbolsPerCodewordMaxField;
            }
            set {
                this.symbolsPerCodewordMaxField = value;
                this.RaisePropertyChanged("symbolsPerCodewordMax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool symbolsPerCodewordMaxSpecified {
            get {
                return this.symbolsPerCodewordMaxFieldSpecified;
            }
            set {
                this.symbolsPerCodewordMaxFieldSpecified = value;
                this.RaisePropertyChanged("symbolsPerCodewordMaxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataMatrixShapeType shape {
            get {
                return this.shapeField;
            }
            set {
                this.shapeField = value;
                this.RaisePropertyChanged("shape");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shapeSpecified {
            get {
                return this.shapeFieldSpecified;
            }
            set {
                this.shapeFieldSpecified = value;
                this.RaisePropertyChanged("shapeSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum Pdf417CompactionModeType {
        
        /// <remarks/>
        text,
        
        /// <remarks/>
        numeric,
        
        /// <remarks/>
        @byte,
        
        /// <remarks/>
        auto,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class QrBarcodeType : BaseBarcodeType {
        
        private QrCodeErrorCorrectionType errorCorrectionField;
        
        private bool errorCorrectionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QrCodeErrorCorrectionType errorCorrection {
            get {
                return this.errorCorrectionField;
            }
            set {
                this.errorCorrectionField = value;
                this.RaisePropertyChanged("errorCorrection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCorrectionSpecified {
            get {
                return this.errorCorrectionFieldSpecified;
            }
            set {
                this.errorCorrectionFieldSpecified = value;
                this.RaisePropertyChanged("errorCorrectionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum QrCodeErrorCorrectionType {
        
        /// <remarks/>
        l,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        q,
        
        /// <remarks/>
        h,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class AztecBarcodeType : BaseBarcodeType {
        
        private int errorCorrectionField;
        
        private bool errorCorrectionFieldSpecified;
        
        private int layersField;
        
        private bool layersFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int errorCorrection {
            get {
                return this.errorCorrectionField;
            }
            set {
                this.errorCorrectionField = value;
                this.RaisePropertyChanged("errorCorrection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorCorrectionSpecified {
            get {
                return this.errorCorrectionFieldSpecified;
            }
            set {
                this.errorCorrectionFieldSpecified = value;
                this.RaisePropertyChanged("errorCorrectionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int layers {
            get {
                return this.layersField;
            }
            set {
                this.layersField = value;
                this.RaisePropertyChanged("layers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool layersSpecified {
            get {
                return this.layersFieldSpecified;
            }
            set {
                this.layersFieldSpecified = value;
                this.RaisePropertyChanged("layersSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class BarcodeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BarcodeTypeAdd addField;
        
        private BarcodeTypeDetect detectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BarcodeTypeAdd add {
            get {
                return this.addField;
            }
            set {
                this.addField = value;
                this.RaisePropertyChanged("add");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BarcodeTypeDetect detect {
            get {
                return this.detectField;
            }
            set {
                this.detectField = value;
                this.RaisePropertyChanged("detect");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class BarcodeTypeAdd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AztecBarcodeType[] aztecField;
        
        private CodabarBarcodeType[] codabarField;
        
        private Code128BarcodeType[] code128Field;
        
        private Code39BarcodeType[] code39Field;
        
        private DataMatrixBarcodeType[] datamatrixField;
        
        private Ean13BarcodeType[] ean13Field;
        
        private Ean8BarcodeType[] ean8Field;
        
        private ItfBarcodeType[] itfField;
        
        private Pdf417BarcodeType[] pdf417Field;
        
        private QrBarcodeType[] qrcodeField;
        
        private UpcaBarcodeType[] upcaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aztec", IsNullable=true, Order=0)]
        public AztecBarcodeType[] aztec {
            get {
                return this.aztecField;
            }
            set {
                this.aztecField = value;
                this.RaisePropertyChanged("aztec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codabar", IsNullable=true, Order=1)]
        public CodabarBarcodeType[] codabar {
            get {
                return this.codabarField;
            }
            set {
                this.codabarField = value;
                this.RaisePropertyChanged("codabar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("code128", IsNullable=true, Order=2)]
        public Code128BarcodeType[] code128 {
            get {
                return this.code128Field;
            }
            set {
                this.code128Field = value;
                this.RaisePropertyChanged("code128");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("code39", IsNullable=true, Order=3)]
        public Code39BarcodeType[] code39 {
            get {
                return this.code39Field;
            }
            set {
                this.code39Field = value;
                this.RaisePropertyChanged("code39");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datamatrix", IsNullable=true, Order=4)]
        public DataMatrixBarcodeType[] datamatrix {
            get {
                return this.datamatrixField;
            }
            set {
                this.datamatrixField = value;
                this.RaisePropertyChanged("datamatrix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ean13", IsNullable=true, Order=5)]
        public Ean13BarcodeType[] ean13 {
            get {
                return this.ean13Field;
            }
            set {
                this.ean13Field = value;
                this.RaisePropertyChanged("ean13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ean8", IsNullable=true, Order=6)]
        public Ean8BarcodeType[] ean8 {
            get {
                return this.ean8Field;
            }
            set {
                this.ean8Field = value;
                this.RaisePropertyChanged("ean8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itf", IsNullable=true, Order=7)]
        public ItfBarcodeType[] itf {
            get {
                return this.itfField;
            }
            set {
                this.itfField = value;
                this.RaisePropertyChanged("itf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pdf417", IsNullable=true, Order=8)]
        public Pdf417BarcodeType[] pdf417 {
            get {
                return this.pdf417Field;
            }
            set {
                this.pdf417Field = value;
                this.RaisePropertyChanged("pdf417");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("qrcode", IsNullable=true, Order=9)]
        public QrBarcodeType[] qrcode {
            get {
                return this.qrcodeField;
            }
            set {
                this.qrcodeField = value;
                this.RaisePropertyChanged("qrcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("upca", IsNullable=true, Order=10)]
        public UpcaBarcodeType[] upca {
            get {
                return this.upcaField;
            }
            set {
                this.upcaField = value;
                this.RaisePropertyChanged("upca");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class BarcodeTypeDetect : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BarcodeSelectionType[] selectionField;
        
        private BarcodeDetectOutputFormatType outputFormatField;
        
        private bool outputFormatFieldSpecified;
        
        private BarcodeDetectInputFormatType inputFormatField;
        
        private bool inputFormatFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selection", IsNullable=true, Order=0)]
        public BarcodeSelectionType[] selection {
            get {
                return this.selectionField;
            }
            set {
                this.selectionField = value;
                this.RaisePropertyChanged("selection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BarcodeDetectOutputFormatType outputFormat {
            get {
                return this.outputFormatField;
            }
            set {
                this.outputFormatField = value;
                this.RaisePropertyChanged("outputFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool outputFormatSpecified {
            get {
                return this.outputFormatFieldSpecified;
            }
            set {
                this.outputFormatFieldSpecified = value;
                this.RaisePropertyChanged("outputFormatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public BarcodeDetectInputFormatType inputFormat {
            get {
                return this.inputFormatField;
            }
            set {
                this.inputFormatField = value;
                this.RaisePropertyChanged("inputFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inputFormatSpecified {
            get {
                return this.inputFormatFieldSpecified;
            }
            set {
                this.inputFormatFieldSpecified = value;
                this.RaisePropertyChanged("inputFormatSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum BarcodeDetectOutputFormatType {
        
        /// <remarks/>
        xml,
        
        /// <remarks/>
        json,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum BarcodeDetectInputFormatType {
        
        /// <remarks/>
        pdf,
        
        /// <remarks/>
        img,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PdfPasswordType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string permissionField;
        
        private string openField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
                this.RaisePropertyChanged("permission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
                this.RaisePropertyChanged("open");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class BillingType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerCodeField;
        
        private string userNameField;
        
        private string applicationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string customerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("customerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
                this.RaisePropertyChanged("applicationName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schema.webpdf.de/1.0/soap/barcode", ConfigurationName="BarcodeService.Barcode")]
    public interface Barcode {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.webpdf.de/1.0/soap/barcode/Barcode/executeRequest", ReplyAction="http://schema.webpdf.de/1.0/soap/barcode/Barcode/executeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(webPDFWebServiceTest.BarcodeService.FaultInfo), Action="http://schema.webpdf.de/1.0/soap/barcode/Barcode/execute/Fault/WebserviceExceptio" +
            "n", Name="WebserviceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBarcodeType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webPDFWebServiceTest.BarcodeService.executeResponse execute(webPDFWebServiceTest.BarcodeService.executeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class operation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BillingType billingField;
        
        private PdfPasswordType passwordField;
        
        private BarcodeType barcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BillingType billing {
            get {
                return this.billingField;
            }
            set {
                this.billingField = value;
                this.RaisePropertyChanged("billing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PdfPasswordType password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public BarcodeType barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("barcode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="execute", WrapperNamespace="http://schema.webpdf.de/1.0/soap/barcode", IsWrapped=true)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/operation", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
        public webPDFWebServiceTest.BarcodeService.operation operation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/barcode", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] fileContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/barcode", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string fileURL;
        
        public executeRequest() {
        }
        
        public executeRequest(webPDFWebServiceTest.BarcodeService.operation operation, byte[] fileContent, string fileURL) {
            this.operation = operation;
            this.fileContent = fileContent;
            this.fileURL = fileURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeResponse", WrapperNamespace="http://schema.webpdf.de/1.0/soap/barcode", IsWrapped=true)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/barcode", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public executeResponse() {
        }
        
        public executeResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BarcodeChannel : webPDFWebServiceTest.BarcodeService.Barcode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BarcodeClient : System.ServiceModel.ClientBase<webPDFWebServiceTest.BarcodeService.Barcode>, webPDFWebServiceTest.BarcodeService.Barcode {
        
        public BarcodeClient() {
        }
        
        public BarcodeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BarcodeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarcodeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarcodeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webPDFWebServiceTest.BarcodeService.executeResponse webPDFWebServiceTest.BarcodeService.Barcode.execute(webPDFWebServiceTest.BarcodeService.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public byte[] execute(webPDFWebServiceTest.BarcodeService.operation operation, byte[] fileContent, string fileURL) {
            webPDFWebServiceTest.BarcodeService.executeRequest inValue = new webPDFWebServiceTest.BarcodeService.executeRequest();
            inValue.operation = operation;
            inValue.fileContent = fileContent;
            inValue.fileURL = fileURL;
            webPDFWebServiceTest.BarcodeService.executeResponse retVal = ((webPDFWebServiceTest.BarcodeService.Barcode)(this)).execute(inValue);
            return retVal.@return;
        }
    }
}
