
package de.webpdf.sample.stubs.ocr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OCRService", targetNamespace = "http://schema.webpdf.de/1.0/soap/ocr", wsdlLocation = "http://localhost:8080/webPDF/soap/ocr?wsdl")
public class OCRService
    extends Service
{

    private final static URL OCRSERVICE_WSDL_LOCATION;
    private final static WebServiceException OCRSERVICE_EXCEPTION;
    private final static QName OCRSERVICE_QNAME = new QName("http://schema.webpdf.de/1.0/soap/ocr", "OCRService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webPDF/soap/ocr?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OCRSERVICE_WSDL_LOCATION = url;
        OCRSERVICE_EXCEPTION = e;
    }

    public OCRService() {
        super(__getWsdlLocation(), OCRSERVICE_QNAME);
    }

    public OCRService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OCRSERVICE_QNAME, features);
    }

    public OCRService(URL wsdlLocation) {
        super(wsdlLocation, OCRSERVICE_QNAME);
    }

    public OCRService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OCRSERVICE_QNAME, features);
    }

    public OCRService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OCRService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OCR
     */
    @WebEndpoint(name = "OCRPort")
    public OCR getOCRPort() {
        return super.getPort(new QName("http://schema.webpdf.de/1.0/soap/ocr", "OCRPort"), OCR.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OCR
     */
    @WebEndpoint(name = "OCRPort")
    public OCR getOCRPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schema.webpdf.de/1.0/soap/ocr", "OCRPort"), OCR.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OCRSERVICE_EXCEPTION!= null) {
            throw OCRSERVICE_EXCEPTION;
        }
        return OCRSERVICE_WSDL_LOCATION;
    }

}
