pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./create-enterprise-service.htm","Erstellung eines Enterprise Services","Erstellung eines Enterprise Services In dem angelegtem Paket erstellen Sie nun einen \"Enterprise Service\". Dies wird mit einem Rechtsklick auf \"Z_...",""],
["./create-soap-package.htm","Anlegen eines Packages im Object Navigator(SE80)","Anlegen eines Packets im Object Manager Im nächsten Schritt legen Sie ein Package für die notwendigen Komponenten an. Wählen Sie dazu \"Paket\" in d...",""],
["./introduction.htm","Einleitung","Einleitung In dieser Anleitung soll anhand einfacher Beispiele, die Einbindung der webPDF SOAP- und REST-Webservices in SAP demonstriert werden. D...",""],
["./links.htm","Links","Links Website https://www.webpdf.de Dokumentation https://www.webpdf.de/dokumentation.html Addressen https://portal.webpdf.de/webPDF/help/doc/de/a...",""],
["./requirements.htm","Voraussetzungen","Voraussetzungen In diesem Kapitel wird Ihnen erläutert, welche Bedingungen Sie auf Ihrem System benötigen, um die später aufgeführten Beispiele um...",""],
["./rest-abap-code.htm","REST ABAP Code","REST ABAP Code *&#38;---------------------------------------------------------------------* *&#38; Report Z_WEBPDF_REST_CONVERT_FILE *&#38;-------------------...",""],
["./rest-example.htm","REST-Beispiel","REST-Beispiel Das nachfolgende Beispiel zeigt, wie Sie die REST-Webservices von webPDF aus SAP heraus verwenden können. Das Beispiel zeigt dies an...",""],
["./rest-usage.htm","Anbindung","Anbindung Starten Sie den SAP Client und starten mit \"se38\" den \"ABAP Editor\" Zunächst müssen Sie ein neues Programm anlegen. Geben Sie dazu den N...",""],
["./sap-demo-system.htm","SAP Entwickler-System (als Demo-System)","SAP Entwickler-System (als Demo-System) Für die nachfolgenden Beispiele können Sie entweder Ihr vorhandenes SAP-System oder die Entwickler-Version...",""],
["./setup-service-consumer.htm","Einbindung als Service-Consumer","Einbindung als Service-Consumer Starten Sie den SAP Client und öffnen Sie danach den \"Object Navigator\". Diesen können Sie über das Befehlsfeld mi...",""],
["./soap-abap-code.htm","SOAP ABAP Code","SOAP ABAP Code *&#38;---------------------------------------------------------------------* *&#38; Report Z_WEBPDF_SOAP_CONVERT_FILE *&#38;-------------------...",""],
["./soap-example.htm","SOAP-Beispiel","SOAP-Beispiel Das nachfolgende Beispiel zeigt, wie Sie die SOAP 1.1 Webservices von webPDF aus SAP heraus verwenden können. Das Beispiel zeigt die...",""],
["./soap-service-activation.htm","Aktivierung und einfacher Test des Service","Aktivierung und einfacher Test des Service Wechseln Sie zurück in den \"Object Navigator\". Darin wählen Sie den angelegten Service-Consumer und öff...",""],
["./soap-service-configuration.htm","Konfiguration des Services über den SOA Manager","Konfiguration des Services über den SOA Manager Öffnen Sie den SOA Manager über das Befehlsfeld dem Transaktioncode \"/osoamanager\" Wählen Sie aus ...",""],
["./soap-usage.htm","Anbindung","Anbindung Starten Sie den SAP Client und starten mit \"se38\" den \"ABAP Editor\" Zunächst müssen Sie ein neues Programm anlegen, um den definierten S...",""],
["./webpdf-installation.htm","Installation webPDF","webPDF Installation Für die nachfolgenden SOAP- und REST-Beispiele wird eine vorhandene webPDF-Installation benötigt. Sie finden den Download für ...",""],
["./what-is-webpdf.htm","Was ist webPDF?","Was ist webPDF? webPDF ist eine serverseitige Lösung für Windows und Linux, die Funktionen für die Konvertierung von Dateiformaten nach PDF und fü...",""]];
