
package de.webpdf.sample.stubs.toolbox;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ToolboxService", targetNamespace = "http://schema.webpdf.de/1.0/soap/toolbox", wsdlLocation = "http://localhost:8080/webPDF/soap/toolbox?wsdl")
public class ToolboxService
    extends Service
{

    private final static URL TOOLBOXSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOOLBOXSERVICE_EXCEPTION;
    private final static QName TOOLBOXSERVICE_QNAME = new QName("http://schema.webpdf.de/1.0/soap/toolbox", "ToolboxService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webPDF/soap/toolbox?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOOLBOXSERVICE_WSDL_LOCATION = url;
        TOOLBOXSERVICE_EXCEPTION = e;
    }

    public ToolboxService() {
        super(__getWsdlLocation(), TOOLBOXSERVICE_QNAME);
    }

    public ToolboxService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOOLBOXSERVICE_QNAME, features);
    }

    public ToolboxService(URL wsdlLocation) {
        super(wsdlLocation, TOOLBOXSERVICE_QNAME);
    }

    public ToolboxService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOOLBOXSERVICE_QNAME, features);
    }

    public ToolboxService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ToolboxService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Toolbox
     */
    @WebEndpoint(name = "ToolboxPort")
    public Toolbox getToolboxPort() {
        return super.getPort(new QName("http://schema.webpdf.de/1.0/soap/toolbox", "ToolboxPort"), Toolbox.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Toolbox
     */
    @WebEndpoint(name = "ToolboxPort")
    public Toolbox getToolboxPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schema.webpdf.de/1.0/soap/toolbox", "ToolboxPort"), Toolbox.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOOLBOXSERVICE_EXCEPTION!= null) {
            throw TOOLBOXSERVICE_EXCEPTION;
        }
        return TOOLBOXSERVICE_WSDL_LOCATION;
    }

}
