//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webPDFWebServiceTest.PdfaService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/soap/pdfa")]
    public partial class FaultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class ZugferdType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] xmlFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] xmlFile {
            get {
                return this.xmlFileField;
            }
            set {
                this.xmlFileField = value;
                this.RaisePropertyChanged("xmlFile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PdfaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PdfaTypeConvert convertField;
        
        private PdfaTypeAnalyze analyzeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PdfaTypeConvert convert {
            get {
                return this.convertField;
            }
            set {
                this.convertField = value;
                this.RaisePropertyChanged("convert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PdfaTypeAnalyze analyze {
            get {
                return this.analyzeField;
            }
            set {
                this.analyzeField = value;
                this.RaisePropertyChanged("analyze");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PdfaTypeConvert : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZugferdType zugferdField;
        
        private PdfaLevelType levelField;
        
        private bool levelFieldSpecified;
        
        private int imageQualityField;
        
        private bool imageQualityFieldSpecified;
        
        private PdfaErrorReportType errorReportField;
        
        private bool errorReportFieldSpecified;
        
        private PdfaSuccessReportType successReportField;
        
        private bool successReportFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ZugferdType zugferd {
            get {
                return this.zugferdField;
            }
            set {
                this.zugferdField = value;
                this.RaisePropertyChanged("zugferd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PdfaLevelType level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
                this.RaisePropertyChanged("levelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int imageQuality {
            get {
                return this.imageQualityField;
            }
            set {
                this.imageQualityField = value;
                this.RaisePropertyChanged("imageQuality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imageQualitySpecified {
            get {
                return this.imageQualityFieldSpecified;
            }
            set {
                this.imageQualityFieldSpecified = value;
                this.RaisePropertyChanged("imageQualitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PdfaErrorReportType errorReport {
            get {
                return this.errorReportField;
            }
            set {
                this.errorReportField = value;
                this.RaisePropertyChanged("errorReport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorReportSpecified {
            get {
                return this.errorReportFieldSpecified;
            }
            set {
                this.errorReportFieldSpecified = value;
                this.RaisePropertyChanged("errorReportSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PdfaSuccessReportType successReport {
            get {
                return this.successReportField;
            }
            set {
                this.successReportField = value;
                this.RaisePropertyChanged("successReport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successReportSpecified {
            get {
                return this.successReportFieldSpecified;
            }
            set {
                this.successReportFieldSpecified = value;
                this.RaisePropertyChanged("successReportSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum PdfaLevelType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1a")]
        Item1a,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1b")]
        Item1b,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2a")]
        Item2a,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2b")]
        Item2b,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2u")]
        Item2u,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3a")]
        Item3a,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3b")]
        Item3b,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3u")]
        Item3u,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum PdfaErrorReportType {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        file,
        
        /// <remarks/>
        message,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum PdfaSuccessReportType {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        zip,
        
        /// <remarks/>
        linked,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PdfaTypeAnalyze : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PdfaLevelType levelField;
        
        private bool levelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PdfaLevelType level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
                this.RaisePropertyChanged("levelSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PdfPasswordType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string permissionField;
        
        private string openField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
                this.RaisePropertyChanged("permission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
                this.RaisePropertyChanged("open");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class BillingType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerCodeField;
        
        private string userNameField;
        
        private string applicationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string customerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("customerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
                this.RaisePropertyChanged("applicationName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schema.webpdf.de/1.0/soap/pdfa", ConfigurationName="PdfaService.Pdfa")]
    public interface Pdfa {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.webpdf.de/1.0/soap/pdfa/Pdfa/executeRequest", ReplyAction="http://schema.webpdf.de/1.0/soap/pdfa/Pdfa/executeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(webPDFWebServiceTest.PdfaService.FaultInfo), Action="http://schema.webpdf.de/1.0/soap/pdfa/Pdfa/execute/Fault/WebserviceException", Name="WebserviceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webPDFWebServiceTest.PdfaService.executeResponse execute(webPDFWebServiceTest.PdfaService.executeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class operation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BillingType billingField;
        
        private PdfPasswordType passwordField;
        
        private PdfaType pdfaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BillingType billing {
            get {
                return this.billingField;
            }
            set {
                this.billingField = value;
                this.RaisePropertyChanged("billing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PdfPasswordType password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PdfaType pdfa {
            get {
                return this.pdfaField;
            }
            set {
                this.pdfaField = value;
                this.RaisePropertyChanged("pdfa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="execute", WrapperNamespace="http://schema.webpdf.de/1.0/soap/pdfa", IsWrapped=true)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/operation", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
        public webPDFWebServiceTest.PdfaService.operation operation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/pdfa", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] fileContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/pdfa", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string fileURL;
        
        public executeRequest() {
        }
        
        public executeRequest(webPDFWebServiceTest.PdfaService.operation operation, byte[] fileContent, string fileURL) {
            this.operation = operation;
            this.fileContent = fileContent;
            this.fileURL = fileURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeResponse", WrapperNamespace="http://schema.webpdf.de/1.0/soap/pdfa", IsWrapped=true)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/pdfa", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public executeResponse() {
        }
        
        public executeResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PdfaChannel : webPDFWebServiceTest.PdfaService.Pdfa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PdfaClient : System.ServiceModel.ClientBase<webPDFWebServiceTest.PdfaService.Pdfa>, webPDFWebServiceTest.PdfaService.Pdfa {
        
        public PdfaClient() {
        }
        
        public PdfaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PdfaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PdfaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PdfaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webPDFWebServiceTest.PdfaService.executeResponse webPDFWebServiceTest.PdfaService.Pdfa.execute(webPDFWebServiceTest.PdfaService.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public byte[] execute(webPDFWebServiceTest.PdfaService.operation operation, byte[] fileContent, string fileURL) {
            webPDFWebServiceTest.PdfaService.executeRequest inValue = new webPDFWebServiceTest.PdfaService.executeRequest();
            inValue.operation = operation;
            inValue.fileContent = fileContent;
            inValue.fileURL = fileURL;
            webPDFWebServiceTest.PdfaService.executeResponse retVal = ((webPDFWebServiceTest.PdfaService.Pdfa)(this)).execute(inValue);
            return retVal.@return;
        }
    }
}
