//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ServiceModel;

namespace webPDFWebServiceTest.ConverterService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/soap/converter")]
    public partial class FaultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        public static implicit operator FaultInfo(FaultException v)
        {
            throw new NotImplementedException();
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConverterTemplateType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class TemplateType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class ConverterTemplateType : TemplateType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class ConverterReportType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool contentProblemsField;
        
        private bool contentProblemsFieldSpecified;
        
        private bool fontAliasUsageField;
        
        private bool fontAliasUsageFieldSpecified;
        
        private bool fontIsMissingField;
        
        private bool fontIsMissingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool contentProblems {
            get {
                return this.contentProblemsField;
            }
            set {
                this.contentProblemsField = value;
                this.RaisePropertyChanged("contentProblems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contentProblemsSpecified {
            get {
                return this.contentProblemsFieldSpecified;
            }
            set {
                this.contentProblemsFieldSpecified = value;
                this.RaisePropertyChanged("contentProblemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool fontAliasUsage {
            get {
                return this.fontAliasUsageField;
            }
            set {
                this.fontAliasUsageField = value;
                this.RaisePropertyChanged("fontAliasUsage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fontAliasUsageSpecified {
            get {
                return this.fontAliasUsageFieldSpecified;
            }
            set {
                this.fontAliasUsageFieldSpecified = value;
                this.RaisePropertyChanged("fontAliasUsageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool fontIsMissing {
            get {
                return this.fontIsMissingField;
            }
            set {
                this.fontIsMissingField = value;
                this.RaisePropertyChanged("fontIsMissing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fontIsMissingSpecified {
            get {
                return this.fontIsMissingFieldSpecified;
            }
            set {
                this.fontIsMissingFieldSpecified = value;
                this.RaisePropertyChanged("fontIsMissingSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class SharePointBridgeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class OfficeBridgeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class ConverterMailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool downloadImagesField;
        
        private bool downloadImagesFieldSpecified;
        
        private bool adjustFontsField;
        
        private bool adjustFontsFieldSpecified;
        
        private AttachmentModeType attachmentModeField;
        
        private bool attachmentModeFieldSpecified;
        
        private bool ignoreMissingBodyChunkField;
        
        private bool ignoreMissingBodyChunkFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool downloadImages {
            get {
                return this.downloadImagesField;
            }
            set {
                this.downloadImagesField = value;
                this.RaisePropertyChanged("downloadImages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool downloadImagesSpecified {
            get {
                return this.downloadImagesFieldSpecified;
            }
            set {
                this.downloadImagesFieldSpecified = value;
                this.RaisePropertyChanged("downloadImagesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool adjustFonts {
            get {
                return this.adjustFontsField;
            }
            set {
                this.adjustFontsField = value;
                this.RaisePropertyChanged("adjustFonts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adjustFontsSpecified {
            get {
                return this.adjustFontsFieldSpecified;
            }
            set {
                this.adjustFontsFieldSpecified = value;
                this.RaisePropertyChanged("adjustFontsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttachmentModeType attachmentMode {
            get {
                return this.attachmentModeField;
            }
            set {
                this.attachmentModeField = value;
                this.RaisePropertyChanged("attachmentMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachmentModeSpecified {
            get {
                return this.attachmentModeFieldSpecified;
            }
            set {
                this.attachmentModeFieldSpecified = value;
                this.RaisePropertyChanged("attachmentModeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ignoreMissingBodyChunk {
            get {
                return this.ignoreMissingBodyChunkField;
            }
            set {
                this.ignoreMissingBodyChunkField = value;
                this.RaisePropertyChanged("ignoreMissingBodyChunk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ignoreMissingBodyChunkSpecified {
            get {
                return this.ignoreMissingBodyChunkFieldSpecified;
            }
            set {
                this.ignoreMissingBodyChunkFieldSpecified = value;
                this.RaisePropertyChanged("ignoreMissingBodyChunkSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum AttachmentModeType {
        
        /// <remarks/>
        embed,
        
        /// <remarks/>
        remove,
        
        /// <remarks/>
        convert,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class ConverterHtmlType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool downloadImagesField;
        
        private bool downloadImagesFieldSpecified;
        
        private bool adjustFontsField;
        
        private bool adjustFontsFieldSpecified;
        
        private string baseURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool downloadImages {
            get {
                return this.downloadImagesField;
            }
            set {
                this.downloadImagesField = value;
                this.RaisePropertyChanged("downloadImages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool downloadImagesSpecified {
            get {
                return this.downloadImagesFieldSpecified;
            }
            set {
                this.downloadImagesFieldSpecified = value;
                this.RaisePropertyChanged("downloadImagesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool adjustFonts {
            get {
                return this.adjustFontsField;
            }
            set {
                this.adjustFontsField = value;
                this.RaisePropertyChanged("adjustFonts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adjustFontsSpecified {
            get {
                return this.adjustFontsFieldSpecified;
            }
            set {
                this.adjustFontsFieldSpecified = value;
                this.RaisePropertyChanged("adjustFontsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string baseURL {
            get {
                return this.baseURLField;
            }
            set {
                this.baseURLField = value;
                this.RaisePropertyChanged("baseURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class SignatureIdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool showSignedByField;
        
        private bool showSignedByFieldSpecified;
        
        private bool showNameField;
        
        private bool showNameFieldSpecified;
        
        private bool showCommonNameField;
        
        private bool showCommonNameFieldSpecified;
        
        private bool showOrganisationUnitField;
        
        private bool showOrganisationUnitFieldSpecified;
        
        private bool showOrganisationNameField;
        
        private bool showOrganisationNameFieldSpecified;
        
        private bool showLocalField;
        
        private bool showLocalFieldSpecified;
        
        private bool showStateField;
        
        private bool showStateFieldSpecified;
        
        private bool showCountryField;
        
        private bool showCountryFieldSpecified;
        
        private bool showMailField;
        
        private bool showMailFieldSpecified;
        
        private bool showDateField;
        
        private bool showDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool showSignedBy {
            get {
                return this.showSignedByField;
            }
            set {
                this.showSignedByField = value;
                this.RaisePropertyChanged("showSignedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showSignedBySpecified {
            get {
                return this.showSignedByFieldSpecified;
            }
            set {
                this.showSignedByFieldSpecified = value;
                this.RaisePropertyChanged("showSignedBySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool showName {
            get {
                return this.showNameField;
            }
            set {
                this.showNameField = value;
                this.RaisePropertyChanged("showName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showNameSpecified {
            get {
                return this.showNameFieldSpecified;
            }
            set {
                this.showNameFieldSpecified = value;
                this.RaisePropertyChanged("showNameSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool showCommonName {
            get {
                return this.showCommonNameField;
            }
            set {
                this.showCommonNameField = value;
                this.RaisePropertyChanged("showCommonName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showCommonNameSpecified {
            get {
                return this.showCommonNameFieldSpecified;
            }
            set {
                this.showCommonNameFieldSpecified = value;
                this.RaisePropertyChanged("showCommonNameSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool showOrganisationUnit {
            get {
                return this.showOrganisationUnitField;
            }
            set {
                this.showOrganisationUnitField = value;
                this.RaisePropertyChanged("showOrganisationUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showOrganisationUnitSpecified {
            get {
                return this.showOrganisationUnitFieldSpecified;
            }
            set {
                this.showOrganisationUnitFieldSpecified = value;
                this.RaisePropertyChanged("showOrganisationUnitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool showOrganisationName {
            get {
                return this.showOrganisationNameField;
            }
            set {
                this.showOrganisationNameField = value;
                this.RaisePropertyChanged("showOrganisationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showOrganisationNameSpecified {
            get {
                return this.showOrganisationNameFieldSpecified;
            }
            set {
                this.showOrganisationNameFieldSpecified = value;
                this.RaisePropertyChanged("showOrganisationNameSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool showLocal {
            get {
                return this.showLocalField;
            }
            set {
                this.showLocalField = value;
                this.RaisePropertyChanged("showLocal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showLocalSpecified {
            get {
                return this.showLocalFieldSpecified;
            }
            set {
                this.showLocalFieldSpecified = value;
                this.RaisePropertyChanged("showLocalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool showState {
            get {
                return this.showStateField;
            }
            set {
                this.showStateField = value;
                this.RaisePropertyChanged("showState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showStateSpecified {
            get {
                return this.showStateFieldSpecified;
            }
            set {
                this.showStateFieldSpecified = value;
                this.RaisePropertyChanged("showStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool showCountry {
            get {
                return this.showCountryField;
            }
            set {
                this.showCountryField = value;
                this.RaisePropertyChanged("showCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showCountrySpecified {
            get {
                return this.showCountryFieldSpecified;
            }
            set {
                this.showCountryFieldSpecified = value;
                this.RaisePropertyChanged("showCountrySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool showMail {
            get {
                return this.showMailField;
            }
            set {
                this.showMailField = value;
                this.RaisePropertyChanged("showMail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showMailSpecified {
            get {
                return this.showMailFieldSpecified;
            }
            set {
                this.showMailFieldSpecified = value;
                this.RaisePropertyChanged("showMailSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool showDate {
            get {
                return this.showDateField;
            }
            set {
                this.showDateField = value;
                this.RaisePropertyChanged("showDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showDateSpecified {
            get {
                return this.showDateFieldSpecified;
            }
            set {
                this.showDateFieldSpecified = value;
                this.RaisePropertyChanged("showDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class SignatureImageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] dataField;
        
        private int opacityField;
        
        private bool opacityFieldSpecified;
        
        private SignatureImagePositionType positionField;
        
        private bool positionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int opacity {
            get {
                return this.opacityField;
            }
            set {
                this.opacityField = value;
                this.RaisePropertyChanged("opacity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opacitySpecified {
            get {
                return this.opacityFieldSpecified;
            }
            set {
                this.opacityFieldSpecified = value;
                this.RaisePropertyChanged("opacitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SignatureImagePositionType position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool positionSpecified {
            get {
                return this.positionFieldSpecified;
            }
            set {
                this.positionFieldSpecified = value;
                this.RaisePropertyChanged("positionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum SignatureImagePositionType {
        
        /// <remarks/>
        center,
        
        /// <remarks/>
        left,
        
        /// <remarks/>
        right,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class SignaturePositionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float widthField;
        
        private bool widthFieldSpecified;
        
        private float heightField;
        
        private bool heightFieldSpecified;
        
        private float xField;
        
        private bool xFieldSpecified;
        
        private float yField;
        
        private bool yFieldSpecified;
        
        private MetricsType metricsField;
        
        private bool metricsFieldSpecified;
        
        private CoordinatesType coordinatesField;
        
        private bool coordinatesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("heightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
                this.RaisePropertyChanged("xSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
                this.RaisePropertyChanged("ySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MetricsType metrics {
            get {
                return this.metricsField;
            }
            set {
                this.metricsField = value;
                this.RaisePropertyChanged("metrics");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metricsSpecified {
            get {
                return this.metricsFieldSpecified;
            }
            set {
                this.metricsFieldSpecified = value;
                this.RaisePropertyChanged("metricsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CoordinatesType coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
                this.RaisePropertyChanged("coordinates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coordinatesSpecified {
            get {
                return this.coordinatesFieldSpecified;
            }
            set {
                this.coordinatesFieldSpecified = value;
                this.RaisePropertyChanged("coordinatesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum MetricsType {
        
        /// <remarks/>
        px,
        
        /// <remarks/>
        mm,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum CoordinatesType {
        
        /// <remarks/>
        pdf,
        
        /// <remarks/>
        user,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class SignatureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SignatureTypeAdd addField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SignatureTypeAdd add {
            get {
                return this.addField;
            }
            set {
                this.addField = value;
                this.RaisePropertyChanged("add");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class SignatureTypeAdd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SignatureTypeAddAppearance appearanceField;
        
        private CertificationLevelType certificationLevelField;
        
        private bool certificationLevelFieldSpecified;
        
        private string fieldNameField;
        
        private string keyNameField;
        
        private string keyPasswordField;
        
        private bool appendSignatureField;
        
        private bool appendSignatureFieldSpecified;
        
        private string locationField;
        
        private string contactField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SignatureTypeAddAppearance appearance {
            get {
                return this.appearanceField;
            }
            set {
                this.appearanceField = value;
                this.RaisePropertyChanged("appearance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CertificationLevelType certificationLevel {
            get {
                return this.certificationLevelField;
            }
            set {
                this.certificationLevelField = value;
                this.RaisePropertyChanged("certificationLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certificationLevelSpecified {
            get {
                return this.certificationLevelFieldSpecified;
            }
            set {
                this.certificationLevelFieldSpecified = value;
                this.RaisePropertyChanged("certificationLevelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("fieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string keyName {
            get {
                return this.keyNameField;
            }
            set {
                this.keyNameField = value;
                this.RaisePropertyChanged("keyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string keyPassword {
            get {
                return this.keyPasswordField;
            }
            set {
                this.keyPasswordField = value;
                this.RaisePropertyChanged("keyPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool appendSignature {
            get {
                return this.appendSignatureField;
            }
            set {
                this.appendSignatureField = value;
                this.RaisePropertyChanged("appendSignature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool appendSignatureSpecified {
            get {
                return this.appendSignatureFieldSpecified;
            }
            set {
                this.appendSignatureFieldSpecified = value;
                this.RaisePropertyChanged("appendSignatureSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class SignatureTypeAddAppearance : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SignaturePositionType positionField;
        
        private SignatureImageType imageField;
        
        private SignatureIdentifierType identifierElementsField;
        
        private string nameField;
        
        private string identifierField;
        
        private int pageField;
        
        private bool pageFieldSpecified;
        
        /// <remarks/>
        public SignaturePositionType position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        public SignatureImageType image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("image");
            }
        }
        
        /// <remarks/>
        public SignatureIdentifierType identifierElements {
            get {
                return this.identifierElementsField;
            }
            set {
                this.identifierElementsField = value;
                this.RaisePropertyChanged("identifierElements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("page");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSpecified {
            get {
                return this.pageFieldSpecified;
            }
            set {
                this.pageFieldSpecified = value;
                this.RaisePropertyChanged("pageSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum CertificationLevelType {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        noChanges,
        
        /// <remarks/>
        formFillingAndSignatures,
        
        /// <remarks/>
        formFillingAndSignaturesAndAnnotations,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class ZugferdType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] xmlFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] xmlFile {
            get {
                return this.xmlFileField;
            }
            set {
                this.xmlFileField = value;
                this.RaisePropertyChanged("xmlFile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PdfaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PdfaTypeConvert convertField;
        
        private PdfaTypeAnalyze analyzeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PdfaTypeConvert convert {
            get {
                return this.convertField;
            }
            set {
                this.convertField = value;
                this.RaisePropertyChanged("convert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PdfaTypeAnalyze analyze {
            get {
                return this.analyzeField;
            }
            set {
                this.analyzeField = value;
                this.RaisePropertyChanged("analyze");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PdfaTypeConvert : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZugferdType zugferdField;
        
        private PdfaLevelType levelField;
        
        private bool levelFieldSpecified;
        
        private int imageQualityField;
        
        private bool imageQualityFieldSpecified;
        
        private PdfaErrorReportType errorReportField;
        
        private bool errorReportFieldSpecified;
        
        private PdfaSuccessReportType successReportField;
        
        private bool successReportFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ZugferdType zugferd {
            get {
                return this.zugferdField;
            }
            set {
                this.zugferdField = value;
                this.RaisePropertyChanged("zugferd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PdfaLevelType level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
                this.RaisePropertyChanged("levelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int imageQuality {
            get {
                return this.imageQualityField;
            }
            set {
                this.imageQualityField = value;
                this.RaisePropertyChanged("imageQuality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imageQualitySpecified {
            get {
                return this.imageQualityFieldSpecified;
            }
            set {
                this.imageQualityFieldSpecified = value;
                this.RaisePropertyChanged("imageQualitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PdfaErrorReportType errorReport {
            get {
                return this.errorReportField;
            }
            set {
                this.errorReportField = value;
                this.RaisePropertyChanged("errorReport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorReportSpecified {
            get {
                return this.errorReportFieldSpecified;
            }
            set {
                this.errorReportFieldSpecified = value;
                this.RaisePropertyChanged("errorReportSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PdfaSuccessReportType successReport {
            get {
                return this.successReportField;
            }
            set {
                this.successReportField = value;
                this.RaisePropertyChanged("successReport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successReportSpecified {
            get {
                return this.successReportFieldSpecified;
            }
            set {
                this.successReportFieldSpecified = value;
                this.RaisePropertyChanged("successReportSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum PdfaLevelType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1a")]
        Item1a,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1b")]
        Item1b,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2a")]
        Item2a,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2b")]
        Item2b,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2u")]
        Item2u,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3a")]
        Item3a,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3b")]
        Item3b,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3u")]
        Item3u,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum PdfaErrorReportType {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        file,
        
        /// <remarks/>
        message,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum PdfaSuccessReportType {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        zip,
        
        /// <remarks/>
        linked,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PdfaTypeAnalyze : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PdfaLevelType levelField;
        
        private bool levelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PdfaLevelType level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
                this.RaisePropertyChanged("level");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
                this.RaisePropertyChanged("levelSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PageType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class MarginType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int leftField;
        
        private bool leftFieldSpecified;
        
        private int rightField;
        
        private bool rightFieldSpecified;
        
        private int topField;
        
        private bool topFieldSpecified;
        
        private int bottomField;
        
        private bool bottomFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool leftSpecified {
            get {
                return this.leftFieldSpecified;
            }
            set {
                this.leftFieldSpecified = value;
                this.RaisePropertyChanged("leftSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int right {
            get {
                return this.rightField;
            }
            set {
                this.rightField = value;
                this.RaisePropertyChanged("right");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rightSpecified {
            get {
                return this.rightFieldSpecified;
            }
            set {
                this.rightFieldSpecified = value;
                this.RaisePropertyChanged("rightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
                this.RaisePropertyChanged("top");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool topSpecified {
            get {
                return this.topFieldSpecified;
            }
            set {
                this.topFieldSpecified = value;
                this.RaisePropertyChanged("topSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int bottom {
            get {
                return this.bottomField;
            }
            set {
                this.bottomField = value;
                this.RaisePropertyChanged("bottom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bottomSpecified {
            get {
                return this.bottomFieldSpecified;
            }
            set {
                this.bottomFieldSpecified = value;
                this.RaisePropertyChanged("bottomSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PageType : MarginType {
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        private int heightField;
        
        private bool heightFieldSpecified;
        
        private MetricsType metricsField;
        
        private bool metricsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("heightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MetricsType metrics {
            get {
                return this.metricsField;
            }
            set {
                this.metricsField = value;
                this.RaisePropertyChanged("metrics");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metricsSpecified {
            get {
                return this.metricsFieldSpecified;
            }
            set {
                this.metricsFieldSpecified = value;
                this.RaisePropertyChanged("metricsSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class ConverterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PageType pageField;
        
        private PdfaType pdfaField;
        
        private SignatureType signatureField;
        
        private ConverterHtmlType htmlField;
        
        private ConverterMailType mailField;
        
        private OfficeBridgeType officeBridgeField;
        
        private SharePointBridgeType sharePointBridgeField;
        
        private ConverterReportType reportField;
        
        private ConverterTemplateType templateField;
        
        private string pagesField;
        
        private bool compressionField;
        
        private bool compressionFieldSpecified;
        
        private int jpegQualityField;
        
        private bool jpegQualityFieldSpecified;
        
        private bool reduceResolutionField;
        
        private bool reduceResolutionFieldSpecified;
        
        private int dpiField;
        
        private bool dpiFieldSpecified;
        
        private bool embedFontsField;
        
        private bool embedFontsFieldSpecified;
        
        private string accessPasswordField;
        
        private string fileExtensionField;
        
        private int maxRecursionField;
        
        private bool maxRecursionFieldSpecified;
        
        /// <remarks/>
        public PageType page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("page");
            }
        }
        
        /// <remarks/>
        public PdfaType pdfa {
            get {
                return this.pdfaField;
            }
            set {
                this.pdfaField = value;
                this.RaisePropertyChanged("pdfa");
            }
        }
        
        /// <remarks/>
        public SignatureType signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("signature");
            }
        }
        
        /// <remarks/>
        public ConverterHtmlType html {
            get {
                return this.htmlField;
            }
            set {
                this.htmlField = value;
                this.RaisePropertyChanged("html");
            }
        }
        
        /// <remarks/>
        public ConverterMailType mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("mail");
            }
        }
        
        /// <remarks/>
        public OfficeBridgeType officeBridge {
            get {
                return this.officeBridgeField;
            }
            set {
                this.officeBridgeField = value;
                this.RaisePropertyChanged("officeBridge");
            }
        }
        
        /// <remarks/>
        public SharePointBridgeType sharePointBridge {
            get {
                return this.sharePointBridgeField;
            }
            set {
                this.sharePointBridgeField = value;
                this.RaisePropertyChanged("sharePointBridge");
            }
        }
        
        /// <remarks/>
        public ConverterReportType report {
            get {
                return this.reportField;
            }
            set {
                this.reportField = value;
                this.RaisePropertyChanged("report");
            }
        }
        
        /// <remarks/>
        public ConverterTemplateType template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
                this.RaisePropertyChanged("template");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
                this.RaisePropertyChanged("pages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool compression {
            get {
                return this.compressionField;
            }
            set {
                this.compressionField = value;
                this.RaisePropertyChanged("compression");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compressionSpecified {
            get {
                return this.compressionFieldSpecified;
            }
            set {
                this.compressionFieldSpecified = value;
                this.RaisePropertyChanged("compressionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int jpegQuality {
            get {
                return this.jpegQualityField;
            }
            set {
                this.jpegQualityField = value;
                this.RaisePropertyChanged("jpegQuality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool jpegQualitySpecified {
            get {
                return this.jpegQualityFieldSpecified;
            }
            set {
                this.jpegQualityFieldSpecified = value;
                this.RaisePropertyChanged("jpegQualitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool reduceResolution {
            get {
                return this.reduceResolutionField;
            }
            set {
                this.reduceResolutionField = value;
                this.RaisePropertyChanged("reduceResolution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reduceResolutionSpecified {
            get {
                return this.reduceResolutionFieldSpecified;
            }
            set {
                this.reduceResolutionFieldSpecified = value;
                this.RaisePropertyChanged("reduceResolutionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int dpi {
            get {
                return this.dpiField;
            }
            set {
                this.dpiField = value;
                this.RaisePropertyChanged("dpi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dpiSpecified {
            get {
                return this.dpiFieldSpecified;
            }
            set {
                this.dpiFieldSpecified = value;
                this.RaisePropertyChanged("dpiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool embedFonts {
            get {
                return this.embedFontsField;
            }
            set {
                this.embedFontsField = value;
                this.RaisePropertyChanged("embedFonts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool embedFontsSpecified {
            get {
                return this.embedFontsFieldSpecified;
            }
            set {
                this.embedFontsFieldSpecified = value;
                this.RaisePropertyChanged("embedFontsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string accessPassword {
            get {
                return this.accessPasswordField;
            }
            set {
                this.accessPasswordField = value;
                this.RaisePropertyChanged("accessPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
                this.RaisePropertyChanged("fileExtension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maxRecursion {
            get {
                return this.maxRecursionField;
            }
            set {
                this.maxRecursionField = value;
                this.RaisePropertyChanged("maxRecursion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxRecursionSpecified {
            get {
                return this.maxRecursionFieldSpecified;
            }
            set {
                this.maxRecursionFieldSpecified = value;
                this.RaisePropertyChanged("maxRecursionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PdfPasswordType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string permissionField;
        
        private string openField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
                this.RaisePropertyChanged("permission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
                this.RaisePropertyChanged("open");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class BillingType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerCodeField;
        
        private string userNameField;
        
        private string applicationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string customerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("customerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
                this.RaisePropertyChanged("applicationName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schema.webpdf.de/1.0/soap/converter", ConfigurationName="ConverterService.Converter")]
    public interface Converter {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.webpdf.de/1.0/soap/converter/Converter/executeRequest", ReplyAction="http://schema.webpdf.de/1.0/soap/converter/Converter/executeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(webPDFWebServiceTest.ConverterService.FaultInfo), Action="http://schema.webpdf.de/1.0/soap/converter/Converter/execute/Fault/WebserviceExce" +
            "ption", Name="WebserviceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TemplateType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarginType))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webPDFWebServiceTest.ConverterService.executeResponse execute(webPDFWebServiceTest.ConverterService.executeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class operation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BillingType billingField;
        
        private PdfPasswordType passwordField;
        
        private ConverterType converterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BillingType billing {
            get {
                return this.billingField;
            }
            set {
                this.billingField = value;
                this.RaisePropertyChanged("billing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PdfPasswordType password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ConverterType converter {
            get {
                return this.converterField;
            }
            set {
                this.converterField = value;
                this.RaisePropertyChanged("converter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="execute", WrapperNamespace="http://schema.webpdf.de/1.0/soap/converter", IsWrapped=true)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/operation", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
        public webPDFWebServiceTest.ConverterService.operation operation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/converter", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] fileContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/converter", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string fileURL;
        
        public executeRequest() {
        }
        
        public executeRequest(webPDFWebServiceTest.ConverterService.operation operation, byte[] fileContent, string fileURL) {
            this.operation = operation;
            this.fileContent = fileContent;
            this.fileURL = fileURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeResponse", WrapperNamespace="http://schema.webpdf.de/1.0/soap/converter", IsWrapped=true)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/converter", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public executeResponse() {
        }
        
        public executeResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConverterChannel : webPDFWebServiceTest.ConverterService.Converter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConverterClient : System.ServiceModel.ClientBase<webPDFWebServiceTest.ConverterService.Converter>, webPDFWebServiceTest.ConverterService.Converter {
        
        public ConverterClient() {
        }
        
        public ConverterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConverterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webPDFWebServiceTest.ConverterService.executeResponse webPDFWebServiceTest.ConverterService.Converter.execute(webPDFWebServiceTest.ConverterService.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public byte[] execute(webPDFWebServiceTest.ConverterService.operation operation, byte[] fileContent, string fileURL) {
            webPDFWebServiceTest.ConverterService.executeRequest inValue = new webPDFWebServiceTest.ConverterService.executeRequest();
            inValue.operation = operation;
            inValue.fileContent = fileContent;
            inValue.fileURL = fileURL;
            webPDFWebServiceTest.ConverterService.executeResponse retVal = ((webPDFWebServiceTest.ConverterService.Converter)(this)).execute(inValue);
            return retVal.@return;
        }
    }
}
