
package de.webpdf.sample.stubs.urlconverter;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "URLConverterService", targetNamespace = "http://schema.webpdf.de/1.0/soap/urlconverter", wsdlLocation = "http://localhost:8080/webPDF/soap/urlconverter?wsdl")
public class URLConverterService
    extends Service
{

    private final static URL URLCONVERTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException URLCONVERTERSERVICE_EXCEPTION;
    private final static QName URLCONVERTERSERVICE_QNAME = new QName("http://schema.webpdf.de/1.0/soap/urlconverter", "URLConverterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webPDF/soap/urlconverter?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        URLCONVERTERSERVICE_WSDL_LOCATION = url;
        URLCONVERTERSERVICE_EXCEPTION = e;
    }

    public URLConverterService() {
        super(__getWsdlLocation(), URLCONVERTERSERVICE_QNAME);
    }

    public URLConverterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), URLCONVERTERSERVICE_QNAME, features);
    }

    public URLConverterService(URL wsdlLocation) {
        super(wsdlLocation, URLCONVERTERSERVICE_QNAME);
    }

    public URLConverterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, URLCONVERTERSERVICE_QNAME, features);
    }

    public URLConverterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public URLConverterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns URLConverter
     */
    @WebEndpoint(name = "URLConverterPort")
    public URLConverter getURLConverterPort() {
        return super.getPort(new QName("http://schema.webpdf.de/1.0/soap/urlconverter", "URLConverterPort"), URLConverter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns URLConverter
     */
    @WebEndpoint(name = "URLConverterPort")
    public URLConverter getURLConverterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schema.webpdf.de/1.0/soap/urlconverter", "URLConverterPort"), URLConverter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (URLCONVERTERSERVICE_EXCEPTION!= null) {
            throw URLCONVERTERSERVICE_EXCEPTION;
        }
        return URLCONVERTERSERVICE_WSDL_LOCATION;
    }

}
