//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webPDFWebServiceTest.OcrService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/soap/ocr")]
    public partial class FaultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class OcrPageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        private int heightField;
        
        private bool heightFieldSpecified;
        
        private MetricsType metricsField;
        
        private bool metricsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("heightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MetricsType metrics {
            get {
                return this.metricsField;
            }
            set {
                this.metricsField = value;
                this.RaisePropertyChanged("metrics");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metricsSpecified {
            get {
                return this.metricsFieldSpecified;
            }
            set {
                this.metricsFieldSpecified = value;
                this.RaisePropertyChanged("metricsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum MetricsType {
        
        /// <remarks/>
        px,
        
        /// <remarks/>
        mm,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class OcrType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OcrPageType pageField;
        
        private OcrLanguageType languageField;
        
        private bool languageFieldSpecified;
        
        private OcrOutputType outputFormatField;
        
        private bool outputFormatFieldSpecified;
        
        private bool checkResolutionField;
        
        private bool checkResolutionFieldSpecified;
        
        private int imageDpiField;
        
        private bool imageDpiFieldSpecified;
        
        private bool forceEachPageField;
        
        private bool forceEachPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OcrPageType page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("page");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OcrLanguageType language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool languageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
                this.RaisePropertyChanged("languageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public OcrOutputType outputFormat {
            get {
                return this.outputFormatField;
            }
            set {
                this.outputFormatField = value;
                this.RaisePropertyChanged("outputFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool outputFormatSpecified {
            get {
                return this.outputFormatFieldSpecified;
            }
            set {
                this.outputFormatFieldSpecified = value;
                this.RaisePropertyChanged("outputFormatSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool checkResolution {
            get {
                return this.checkResolutionField;
            }
            set {
                this.checkResolutionField = value;
                this.RaisePropertyChanged("checkResolution");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool checkResolutionSpecified {
            get {
                return this.checkResolutionFieldSpecified;
            }
            set {
                this.checkResolutionFieldSpecified = value;
                this.RaisePropertyChanged("checkResolutionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int imageDpi {
            get {
                return this.imageDpiField;
            }
            set {
                this.imageDpiField = value;
                this.RaisePropertyChanged("imageDpi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool imageDpiSpecified {
            get {
                return this.imageDpiFieldSpecified;
            }
            set {
                this.imageDpiFieldSpecified = value;
                this.RaisePropertyChanged("imageDpiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool forceEachPage {
            get {
                return this.forceEachPageField;
            }
            set {
                this.forceEachPageField = value;
                this.RaisePropertyChanged("forceEachPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forceEachPageSpecified {
            get {
                return this.forceEachPageFieldSpecified;
            }
            set {
                this.forceEachPageFieldSpecified = value;
                this.RaisePropertyChanged("forceEachPageSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum OcrLanguageType {
        
        /// <remarks/>
        eng,
        
        /// <remarks/>
        deu,
        
        /// <remarks/>
        fra,
        
        /// <remarks/>
        ita,
        
        /// <remarks/>
        spa,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public enum OcrOutputType {
        
        /// <remarks/>
        text,
        
        /// <remarks/>
        hocr,
        
        /// <remarks/>
        pdf,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class PdfPasswordType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string permissionField;
        
        private string openField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string permission {
            get {
                return this.permissionField;
            }
            set {
                this.permissionField = value;
                this.RaisePropertyChanged("permission");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
                this.RaisePropertyChanged("open");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class BillingType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerCodeField;
        
        private string userNameField;
        
        private string applicationNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string customerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("customerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string applicationName {
            get {
                return this.applicationNameField;
            }
            set {
                this.applicationNameField = value;
                this.RaisePropertyChanged("applicationName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schema.webpdf.de/1.0/soap/ocr", ConfigurationName="OcrService.OCR")]
    public interface OCR {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://schema.webpdf.de/1.0/soap/ocr/OCR/executeRequest", ReplyAction="http://schema.webpdf.de/1.0/soap/ocr/OCR/executeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(webPDFWebServiceTest.OcrService.FaultInfo), Action="http://schema.webpdf.de/1.0/soap/ocr/OCR/execute/Fault/WebserviceException", Name="WebserviceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webPDFWebServiceTest.OcrService.executeResponse execute(webPDFWebServiceTest.OcrService.executeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schema.webpdf.de/1.0/operation")]
    public partial class operation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BillingType billingField;
        
        private PdfPasswordType passwordField;
        
        private OcrType ocrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BillingType billing {
            get {
                return this.billingField;
            }
            set {
                this.billingField = value;
                this.RaisePropertyChanged("billing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PdfPasswordType password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OcrType ocr {
            get {
                return this.ocrField;
            }
            set {
                this.ocrField = value;
                this.RaisePropertyChanged("ocr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="execute", WrapperNamespace="http://schema.webpdf.de/1.0/soap/ocr", IsWrapped=true)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/operation", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schema.webpdf.de/1.0/operation")]
        public webPDFWebServiceTest.OcrService.operation operation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/ocr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] fileContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/ocr", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string fileURL;
        
        public executeRequest() {
        }
        
        public executeRequest(webPDFWebServiceTest.OcrService.operation operation, byte[] fileContent, string fileURL) {
            this.operation = operation;
            this.fileContent = fileContent;
            this.fileURL = fileURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeResponse", WrapperNamespace="http://schema.webpdf.de/1.0/soap/ocr", IsWrapped=true)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schema.webpdf.de/1.0/soap/ocr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public executeResponse() {
        }
        
        public executeResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OCRChannel : webPDFWebServiceTest.OcrService.OCR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OCRClient : System.ServiceModel.ClientBase<webPDFWebServiceTest.OcrService.OCR>, webPDFWebServiceTest.OcrService.OCR {
        
        public OCRClient() {
        }
        
        public OCRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OCRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OCRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OCRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webPDFWebServiceTest.OcrService.executeResponse webPDFWebServiceTest.OcrService.OCR.execute(webPDFWebServiceTest.OcrService.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public byte[] execute(webPDFWebServiceTest.OcrService.operation operation, byte[] fileContent, string fileURL) {
            webPDFWebServiceTest.OcrService.executeRequest inValue = new webPDFWebServiceTest.OcrService.executeRequest();
            inValue.operation = operation;
            inValue.fileContent = fileContent;
            inValue.fileURL = fileURL;
            webPDFWebServiceTest.OcrService.executeResponse retVal = ((webPDFWebServiceTest.OcrService.OCR)(this)).execute(inValue);
            return retVal.@return;
        }
    }
}
